version: 2
updates:

  # Python (pip)
  - package-ecosystem: pip
    directory: "/" # Update requirements.txt or setup.py in the root directory
    schedule:
      interval: "daily"

  # Other (if applicable; choose appropriate ecosystems)
  - package-ecosystem: github-actions
    directory: "/" # Automatically update GitHub Action workflows
    schedule:
      interval: "daily"
