pull_request_rules:
  - name: Automatic merge when CI passes and reviews approve
    conditions:
      - check-success=CI # replace "CI" with the name of your CI status check
    actions:
      merge:
        method: merge
