name: Auto Merge

on:
  schedule:
    - cron: '*/1 * * * *'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Loop to run every 15 seconds
        run: |
          for i in {1..4}; do
            echo "Running auto-merge check #$i"
            gh api repos/${{ github.repository }}/pulls | jq -r '.[] | select(.state=="open") | .head.sha' | while read sha; do
              checks=$(gh api repos/${{ github.repository }}/commits/$sha/check-runs)
              allChecksPassed=$(echo $checks | jq -r '.check_runs | map(select(.conclusion == "success")) | length == (. | length)')
              if [ "$allChecksPassed" = "true" ]; then
                gh pr merge $sha --squash --admin
              fi
            done
            sleep 15
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
