name: Auto Pull Request

on:
  push:
    branches-ignore:
      - main
  schedule:
    - cron: "*/1 * * * *"  # This runs every minute

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Extract branch name without newlines or extra characters
      - name: Get branch name
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | tr -d '\n' | tr -d '\r')
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      # Step 3: Ensure we are not on main
      - name: Ensure we're not on main
        run: |
          if [ "${{ env.BRANCH_NAME }}" == "main" ]; then
            echo "We are on main, no pull request will be created."
            exit 0
          fi

      # Step 4: Fetch main branch and check if current branch is behind
      - name: Check if branch is behind main
        run: |
          git fetch origin main
          BEHIND=$(git rev-list --count HEAD..origin/main)
          echo "BEHIND=$BEHIND" >> $GITHUB_ENV
          if [ "$BEHIND" -gt 0 ]; then
            echo "Branch is behind main by $BEHIND commits"
          else
            echo "Branch is up to date with main"
            exit 0
          fi
        continue-on-error: true

      # Step 5: Get latest commit message
      - name: Get latest commit message
        id: commit_message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
          echo "commit-message=$COMMIT_MESSAGE" >> $GITHUB_ENV

      # Step 6: Create a pull request to merge into main
      - name: Create Pull Request
        id: create_pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_OUTPUT=$(gh pr create \
            --title "Auto Pull Request - ${{ env.BRANCH_NAME }}" \
            --body "${{ env.commit-message }}" \
            --base main \
            --head "${{ env.BRANCH_NAME }}" \
            --repo "${{ github.repository }}")
          echo "PR_OUTPUT=$PR_OUTPUT" >> $GITHUB_ENV
          echo "PR_URL=$(echo "$PR_OUTPUT" | grep -o 'http.*$')" >> $GITHUB_ENV

      # Step 7: Add 'github_actions' and 'Auto Merge' labels to the pull request
      - name: Add 'github_actions' and 'Auto Merge' labels
        run: |
          if [ -n "${{ env.PR_URL }}" ]; then
            PR_NUMBER=$(echo "${{ env.PR_OUTPUT }}" | grep -o '[0-9]*')
            gh pr edit "$PR_NUMBER" --add-label "github_actions" --add-label "Auto Merge"
          else
            echo "No pull request created."
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
