name: Auto Merge

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Wait for security checks
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            const checks = await github.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: pr.head.sha
            });
            const allChecksPassed = checks.data.check_runs.every(check => check.conclusion === 'success');
            if (!allChecksPassed) {
              core.setFailed('Not all security checks have passed.');
            }

      - name: Auto-merge pull request
        if: success()
        uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mergeMethod: squash
          commitMessage: "Auto-merged by GitHub Actions"
