name: Create Issue from Discord Bot

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Title of the issue'
        required: true
        type: string
      body:
        description: 'Body of the issue'
        required: false
        type: string

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: ${{ github.event.inputs.title }}
          body: ${{ github.event.inputs.body }}
