name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to get the README.md
      - name: Checkout code
        uses: actions/checkout@v2

      # Install pandoc to convert README.md to HTML
      - name: Install pandoc
        run: sudo apt-get install -y pandoc

      # Create HTML from README.md
      - name: Convert README.md to index.html
        run: |
          pandoc README.md -o index.html

      # Deploy to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
