name: Run ELO.py

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-elo:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # Specify your Python version here
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # If you have dependencies listed in a requirements.txt file
    
    - name: Run ELO.py
      run: |
        python ELO.py
