name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: sudo apt-get install -y autoconf automake libtool

    - name: Generate configure script
      run: autoreconf -i

    - name: Configure the project
      run: ./configure

    - name: Build the project
      run: make

    - name: Run tests
      run: make check
